language: python
python:
  - "3.7"
  - "3.8"
env:
  global:
    - PYTHON_VERSION=$TRAVIS_PYTHON_VERSION
    - MAIN_CMD="pytest"
    - CONDA_DEPENDENCIES="pytest-cov coveralls coverage codecov pyresample setuptools"
    - PIP_DEPENDENCIES=""
    - CONDA_CHANNELS="conda-forge"
    - CONDA_CHANNEL_PRIORITY="strict"
    - SETUP_XVFB=False
    - EVENT_TYPE="push pull_request"
install:
  - git clone --depth 1 git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda.sh
  - pip install -e .
script:
  - $MAIN_CMD $SETUP_CMD
after_success:
  - coveralls
  - codecov
